### ISSUE TITLE
sensors unavailable after mqtt rework from HA devs

### ISSUE THREAD

**Issue by tismofied** [makeitworktech/home-assistant-config#2]
you mind sharing how you got your yaml setup? I have automate posting to home assistant successfully but sensors are unavailable on home assistant. I already moved the main sensor to mqtt.yaml but it's not working

**Comment by tismofied** [comment]
I had to recreate the HA token because i believe the automate app changed quite a bit. its fixed now.

**Comment by makeitworktech** [comment]
Sorry I missed this. Glad you got it!
